version: '2.1'

services:
  mqserver:
    image: ibmcom/mq:9.1.5.0-r1
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    ports:
      - "1414:1414"
      - "9443:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/ibmmq/console"]
      interval: 10s
      timeout: 5s
      retries: 6